### ISSUE TITLE
Images not being displayed properly

### ISSUE THREAD

**Issue by docfactory37** [Starbix/dockerimages#10]
I have set up your nextcloud docker container up but its not displaying correctly could you please help regarding a slousion or if it is a setup issue.

![image](https://user-images.githubusercontent.com/20963053/83835016-0c509600-a733-11ea-9741-ed0bacca8aa7.png)

when you add the adon Side menu it becomes unuseable 

![image](https://user-images.githubusercontent.com/20963053/83835086-3ace7100-a733-11ea-8d6d-2a26c52ca936.png)

**Comment by Starbix** [comment]
Can you share the errors displayed in the Browser Console?
