### ISSUE TITLE
Every Update or Change seems to default it back to factory

### ISSUE THREAD

**Issue by dazza120** [Starbix/dockerimages#2]
Hi every update via a pull from unraid or a change of the config seems to, revert the whole home bridge back to the factory settings that cause homebridge to fail to start as it detects the json file which is setup for my wemo and nest stuff. So i have to remove the json file then restart the home bridge then terminal in and install the plugins then put the json file back. Is there anyway i can get unraid to keep my setting on update so home bridge remains operational after pulling your updates. PS thanks for the port.

**Comment by Starbix** [comment]
Hello @dazza120 

First of all thanks for showing interest in my image!
Right now it only installs the homebridge plugin (at the building stage of the image). However I could add an option where the starting script installs additional plugins, so you could use wemo and nest.

**Comment by dazza120** [comment]
yes please that would be great thanks. The unraid port is working well thanks!

**Comment by dazza120** [comment]
Hi the ones i'm using is npm install -g homebridge-nest and npm install -g homebridge-platform-wemo if these could be pulled down with every update it would save my home bridge going off line. Thanks in advance

**Comment by Starbix** [comment]
You can now add custom plugins using the CUSTOMPLUGINS environmental variable like this:
<img width="1047" alt="" src="https://user-images.githubusercontent.com/12443257/40989048-f112efe0-68ec-11e8-8ba0-f3e624783d1a.png">

Please tell me if this works for you.

**Comment by dazza120** [comment]
Hi for some reason its not pulling down the plugins it, just fails to start i have done it like this

Config Type: Variable

Name: Host Key 1

Key:

Value:

Default Value: homebridge-nest homebridge-platform-wemo

Description:Container Variable: CUSTOMPLUGINS

Display: Always

Required: Yes

Password Mask: No

**Comment by Starbix** [comment]
You need to put it into `Value`. You put it into `Default Value` and `Key` needs to be `CUSTOMPLUGINS`. 

<img width="600" alt="bildschirmfoto 2018-06-05 um 22 36 50" src="https://user-images.githubusercontent.com/12443257/41001367-f94e1468-6910-11e8-95a8-6f7fa89d6c0c.png">

**Comment by dazza120** [comment]
hi thanks do you need the npm install -g part or just from homebridge-platform-wemo? replied before me thank you

**Comment by Starbix** [comment]
Just the name. The init script executes `npm install -g` + CUSTOMPLUGINS

**Comment by dazza120** [comment]
its saved it just won't start. because its no downloading them before it starts the json file blocks it here is how i have it

   <Volume>
      <HostDir>/mnt/user/appdata/homebridge/</HostDir>
      <ContainerDir>/config</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
  </Data>
  <Environment>
    <Variable>
      <Value>homebridge-nest homebridge-platform-wemo </Value>
      <Name>Custom Plugins</Name>
      <Mode/>
    </Variable>
  </Environment>
  <Labels/>
  <Config Name="Host Port 1" Target="51826" Default="51826" Mode="tcp" Description="Container Port: 51826" Type="Port" Display="always" Required="true" Mask="false">51826</Config>
  <Config Name="Host Key 1" Target="Custom Plugins" Default="" Mode="" Description="Container Variable: CUSTOMPLUGINS" Type="Variable" Display="always" Required="false" Mask="false">homebridge-nest homebridge-platform-wemo </Config>
  <Config Name="AppData Config Path" Target="/config" Default="/mnt/user/appdata/" Mode="rw" Description="Container Path: /config" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/homebridge/</Config>
</Container>

**Comment by dazza120** [comment]
<Environment>
    <Variable>
      <Value>homebridge-nest homebridge-platform-wemo </Value>
      <Name>Custom Plugins</Name>
      <Mode/>
    </Variable>
  </Environment>
  <Labels/>

**Comment by dazza120** [comment]
![screen shot 2018-06-05 at 21 53 00](https://user-images.githubusercontent.com/30567715/41002199-fe618314-690a-11e8-889b-42b809f773fd.png)

**Comment by Starbix** [comment]
It's CUSTOMPLUGINS not Custom Plugins as the Key!

**Comment by dazza120** [comment]
Hi i've done that. Now it starts but there is no log or home kit function

**Comment by dazza120** [comment]
Scratch that the log has loaded and it has downloaded the plugins :)

**Comment by dazza120** [comment]
Thank You very much now when it updates i won't have to worry about the json file thank you very much it is much appreciated

**Comment by Starbix** [comment]
Glad this worked for you!
