### ISSUE TITLE
Can't install Docker in unRAID

### ISSUE THREAD

**Issue by BinsonBuzz** [Starbix/dockerimages#8]
Hi I'm having a go at installing this but I'm getting this error:

`/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: "root": executable file not found in $PATH": unknown.`

Any ideas how to fix please?

Thanks

**Comment by Starbix** [comment]
What exactly are you trying to install? Docker itself or one of the containers in this repo? You need to send the command it's executing beforehand so I can help you.

**Comment by BinsonBuzz** [comment]
Sorry - I didn't get an alert that you'd replied.

Here's the full Command:

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='LDAPforPlex' --net='br0.55' --ip='192.168.50.90' --cpuset-cpus='1,7,8,17,23,24' --log-opt max-size='50m' --log-opt max-file='3' --privileged=true -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'TOKEN'='xxxxxxxxxxx' -e 'MACHINEID'='xxxxxxxxxxxxx' -e 'SERVERNAME'='Highlander' -e 'UDP_PORT_2389'='2389' -e 'DEBUG'='true' 'starbix/plex-ldap' root
f7991cdcf4f2d544b18d3ced46495d80c7a57b88b85b85f26cff94528cb46d32
/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: "root": executable file not found in $PATH": unknown.

The command failed.
```

**Comment by Starbix** [comment]
The `root` at the end of the command is superflous. It tries to execute a binary called `root` in the container, which doesn't exist. You need to try to remove that.
Also, is there any reason you run this container privileged?

**Comment by BinsonBuzz** [comment]
duh - I don't even know where the 'root' came from - deleted.  I tried privileged because of the error - all sorted now.  Thanks
